### ISSUE TITLE
Feedzirra::Feed.fetch_and_parse throws an error and returns nil on Heroku

### ISSUE THREAD

**Issue by okolehao** [feedjira/feedjira#167]
Localhost works, but whenever we push to Heroku Feedzirra fails 

/app/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.6.147/lib/new_relic/agent/instrumentation/curb.rb:106: warning: uncaught exception from callback 

and throws this error shown above.

**Comment by thefonso** [comment]
Following this nice tutorial....https://binarapps.com/blog/feedjira-with-rails/

Full app code on github here...https://github.com/binarapps/feedjira-with-rails

I'm getting this error...

/Users/xxxxx/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/feedjira-1.3.0/lib/feedjira/feed.rb:237: warning: uncaught exception from callback

can you assist?
