### ISSUE TITLE
Parsing RSS feed image 

### ISSUE THREAD

**Issue by zealot128** [feedjira/feedjira#193]
I wonder if it is possible to parse out the "image > url" of the top RSS feed image

``` xml
<rss><channel>...
 <image>
    <title>oreillyblog » Podcast</title>
    <url>http://community.oreilly.de/blog/wp-content/uploads/2010/06/logo_kolophon_172x172.jpg</url>
    <link>http://community.oreilly.de/blog/category/podcast/</link>
 </image>
```

I tried:

``` ruby
Feedzirra::Feed.add_common_feed_element "image > url", :as => :image1 
Feedzirra::Feed.add_common_feed_element "image url", :as => :image2  
Feedzirra::Feed.add_common_feed_element "url", :as => :image3
```

only `feed.image3` yields the correct result. 
But I find 'url' a bit generic. 

Is it possible to tell SAX machine to look inside nested elements?

**Comment by amitsaxena** [comment]
@zealot128 were you able make that work, i.e. parse nested elements properly? Were you able to get image > url, image > title and image > link separately?
