### ISSUE TITLE
Impossible to use with jruby because of curb dependency

### ISSUE THREAD

**Issue by heaven** [feedjira/feedjira#208]
Curb cannot be used with jruby, is it possible to add fallback to Net::HTTP if curb is not installed?

**Comment by jonallured** [comment]
Bump!

My plan is to pull the `faraday` branch into master this week and then cut a 2.0 release in the near future, so now is the time for any feedback you might have.

Thanks!
Jon

**Comment by RKushnir** [comment]
Hi, how is it going? I'm really looking forward to the faraday support. Thank you.

**Comment by jonallured** [comment]
Well, I finally got version 2.0 out the door with support for jRuby!! :smile:

**Comment by RKushnir** [comment]
@jonallured Congratulations! Looking forward to update my app :)
