### ISSUE TITLE
Where does Feedjira store feed information for "update"?

### ISSUE THREAD

**Issue by funkenstrahlen** [feedjira/feedjira#209]
Does this info get lost when I "restart" the application? How can I make it persistent?

**Comment by tomsihap** [comment]
Hi. Is there any update ? I got returned "undefined method `update' for Feedjira::Feed:Class"

**Comment by jonallured** [comment]
Hi @tomsihap, the `update` method was removed from Feedjira with version 2.0. Maybe let me know what you're trying to do and I could help, but basically - Feedjira updating isn't a great approach. That logic should be in your application.

Thanks!
Jon

**Comment by tomsihap** [comment]
Hi @jonallured . 
Turns out it was a PEBCAK error. The RSS feed wasn't up to date itself.
Feedjira updates the feed correctly without no update method, no issue then !
