### ISSUE TITLE
Thoughts on Version 2.0

### ISSUE THREAD

**Issue by jonallured** [feedjira/feedjira#221]
I wrote a [blog post](http://feedjira.com/blog/2014/04/14/thoughts-on-version-two-point-oh.html) outlining some of my thoughts for the next version of Feedjira, which will be a fairly major rewrite.

In that post, I asked for your feedback, so please feel free to share! :heart: :heart: :heart:

**Comment by amatriain** [comment]
I've tested my app using the 'faraday' branch of Feedjira. Tests are passing and after some manual testing I've found no issues.

I'm not fetching feeds with this gem though, I only use Feedjira for its parsing capabilities and do the fetching with an HTTP client gem, so take my feedback with a grain of salt. But at least I can confirm that feed parsing is not affected by the switch from curb to faraday.

**Comment by jonallured** [comment]
Thanks for the feedback @amatriain! If anyone else has anything for me on this - now is your chance. My plan is to pull the `faraday` branch into master this week and in the near future cut a 2.0 release.

Thanks!
Jon

**Comment by monvural** [comment]
What about quality of what gets parsed? Often times there are relative links that don't render properly. We don't get any styles with the content (which is a limitation of the feeds), but it can break how things are parsed.

If there are ways to improve the quality of the output, then I'm happy to volunteer to help with those pieces.

**Comment by jonallured** [comment]
OMG, I just released version 2.0!!

http://feedjira.com/blog/2015/06/05/feedjira-two-point-oh.html

Thanks for everyone's input and help with testing!! :heart: :heart: :heart:
