### ISSUE TITLE
Feed to_json returns abnormal JSON

### ISSUE THREAD

**Issue by pangolingo** [feedjira/feedjira#240]
When I create a feed object or set of feeds (using Feedjira::Feed.parse) and call to_json, it doesn't return usable JSON. Each attribute/value pair is inside an array.

Expectation:
each feed entry should become a hash.

**Comment by kookster** [comment]
fwiw - I found there is a `to_h` method on the entry, so you can do `entry.to_h.to_json` and get the json for the entry
