### ISSUE TITLE
:on_failure callback is never called

### ISSUE THREAD

**Issue by treinamento-infosimples** [feedjira/feedjira#253]
Hi,

First of all, thanks for Feedjira! We've been using it in a project and it's been working great!

Now, to the issue :)
I've narrowed down the problem to this simple example:

```ruby
xml = <<-XML
  <?xml version="1.0" encoding="UTF-8" ?>
  <rss version="2.0">
  <channel>
   <title>RSS Title</title>
   <item>
    <description>Here is an invalid character: \xE9!</description>
   </item>
  </channel>
  </rss>
XML

# Force Feedjira::Parser::RSS.able_to_parse? to return true
xml.force_encoding("ASCII-8BIT")

# Callback that is supposed to be called
callback = ->(*args) { puts "Callback was called with args: "; puts args.inspect }

# This line should cause callback to be called, but nothing happens
Feedjira::Feed.parse(xml, &callback)
```

-----------------------------------------------------------------------------

I believe the problem is [here](https://github.com/feedjira/feedjira/blob/master/lib/feedjira/feed_utilities.rb#L16):

```ruby
# lib/feedjira/feed_utilities.rb:16
# Current line:
super xml, &block

# What I think it should read:
super xml, block
```

... because the [super method](https://github.com/pauldix/sax-machine/blob/v1.0.3/lib/sax-machine/sax_document.rb#L38) doesn't take a block, it takes a splat argument. This is the point where the callback is lost.

This fix definitely works for Feedjira::Parser::RSS and others that use SAXMachine, but I don't know if it could break other library calls, so I would like to know if you agree with the fix before I submit a pull request.

Thanks!

**Comment by jonallured** [comment]
Hi @deborasetton, I'm going to go ahead and close this issue for now. Let me know if you end up needing anything else on it.

**Comment by deborasetton** [comment]
Hi @jonallured, I ended up not working on this issue anymore, unfortunately. Thanks for the notice.
