### ISSUE TITLE
Extending Feeds

### ISSUE THREAD

**Issue by lustremedia** [feedjira/feedjira#257]
I am looking for a library in ruby that I can use to extend rss feeds to make it compatible with itunes. Is that possible with feedjira? Is there something build in that does that already?

**Comment by jonallured** [comment]
Hi @lustremedia, I'm not 100% sure I understand your question, but I think you're asking about authoring a feed that's iTunes compatible, right? If so, Feedjira is not the library for you - Feedjira is focused on fetching and parsing feeds. It's a great library to use if you want to build a feed reader or something similar.

Hope that helps and let me know if you have any further questions!
Jon

**Comment by lustremedia** [comment]
Hi @jonallured what I need to do is fetch a wordpress rss feed and prepare it for iTunes submittal. This would involve adding several attributes and extra fields to the wordpress feed. http://www.apple.com/itunes/podcasts/specs.html#rss

From what I have seen on the pages of feedjira I think it should be no problem, but I was wondering if feedjira would have any functions build in that would convert an atom or rss2.0 feed into an itunes feed automatically, but I guess not ...

**Comment by jonallured** [comment]
Ok, gotcha - yeah, Feedjira doesn't have anything to support converting a feed from one format to another. Good luck!!
