### ISSUE TITLE
Weird situation where feed fetched is just 200 (fixnum)

### ISSUE THREAD

**Issue by concept47** [feedjira/feedjira#259]
Feedjira::Feed.fetch_and_parse 'http://www.sunnewsonline.com/index.php?format=feed&type=rss'

returns 200 instead of a feed object.

I'm guessing that isn't supposed to be the case?

**Comment by jonallured** [comment]
Hi @concept47, looks like you got a bad URL:

```
$ curl -I 'http://www.sunnewsonline.com/index.php?format=feed&type=rss'
HTTP/1.1 301 Moved Permanently
...
Content-Type: text/html; charset=iso-8859-1
```

Which points to this URL:

```
$ curl -I 'http://sunnewsonline.com/new/?format=feed&type=rss'
HTTP/1.1 200 OK
...
Content-Type: text/html; charset=UTF-8
```

Which isn't an RSS feed, it's just an HTML page.

I'll agree that returning a 200 here totally sucks, but you get a clearer picture of what's happening like this:

```ruby
> raw_content = Feedjira::Feed.fetch_raw 'http://www.sunnewsonline.com/index.php?format=feed&type=rss'
> feed = Feedjira::Feed.parse raw_content
# => Feedjira::NoParserAvailable: No valid parser for XML.
```

That's better - no parser is available because `raw_content` is not actually a feed.

Hope that helps!! :D

**Comment by concept47** [comment]
:+1:

**Comment by jonallured** [comment]
OMG, totally!! Have you seen the faraday branch? If you have a chance, check it out - I replaced curb with faraday and that allowed me to restructure some stuff. Here's what I get when I `fetch_and_parse` over on that branch:

```ruby
feed = Feedjira::Feed.fetch_and_parse 'http://www.sunnewsonline.com/index.php?format=feed&type=rss'
# => Feedjira::FetchFailure: Fetch failed - 301
feed = Feedjira::Feed.fetch_and_parse 'http://sunnewsonline.com/new/?format=feed&type=rss'
# => Feedjira::NoParserAvailable: No valid parser for XML.
```

Actually helpful Exceptions! With something like this, you'd be able to detect problems and decide in your application's business logic how you'd like to handle them.

Better, right?

**Comment by concept47** [comment]
> Better, right?

Absolutely. Thank you!

**Comment by jonallured** [comment]
Cool, I'm going to go ahead and close this issue - look for that branch to land as version 2.0 at some point. :smile:
