### ISSUE TITLE
What to do with feeds with no images

### ISSUE THREAD

**Issue by bdubaut** [feedjira/feedjira#260]
Some RSS feeds generated by several blog engines are ignoring the image element (http://cyber.law.harvard.edu/rss/rss.html#ltimagegtSubelementOfLtchannelgt) which is an optional sub-element of channel. I encountered this as I am creating a news platform, and I need images from the article to make it pretty. 

My solution would be something like this:
```ruby
if feed.image.nil?
  array = parse_HTML_and_get_images(feed.description)
  feed.image = best_image_of_the(array)
end
```

What do you guys think?

**Comment by amatriain** [comment]
Can you give examples of feeds in which this is happening?

**Comment by jonallured** [comment]
I think your code example looks like a fine approach. But yeah, there's nothing Feedjira can do if the author of the feed doesn't include the image. You could also have a default image.

Anyway, good luck!

**Comment by bdubaut** [comment]
@amatriain here one gist of an example of a Ghost blog. https://gist.github.com/bdubaut/8000ed960c5a0f05114f
I couldn't find any ghost blog doing so, and after discussing with them on Twitter, they said it's an error on their side.
I did the same thing with my wordpress blog (www.careforadrink.com) and I have the same result. 
Hence me proposing to find an image from the entry if the feed does not include one.

**Comment by amatriain** [comment]
Ok, I see what you mean. I agree with @jonallured, I don't think Feedjira should attempt to "fix" a missing optional element; if it's optional then it's not an error if it's missing. Any attempt to guess a correct value would be application-specific, in my opinion.

**Comment by amatriain** [comment]
Also I see some problems with your idea. Currently the RSS parser Feedjira uses (https://github.com/feedjira/feedjira/blob/master/lib/feedjira/parser/rss.rb) ignores the ```image``` element in the xml, and there is no method on the ruby object named ```image```: 

```
> f = Feedjira::Feed.fetch_and_parse 'http://www.autodidacts.io/rss/'
> f.image
NoMethodError: undefined method `image' for #<Feedjira::Parser::RSS:0x000000069d08e0>
```

So Feedjira doesn't support the ```image``` element even for RSS feeds that include it. It may be interesting to add support for this for RSS feeds (and other types of feeds that include a similar element). @bdubaut , do you have an example of a feed that does include this element? I may submit a PR when I have the time, unless somebody else does it first.

**Comment by jonallured** [comment]
Hi @bdubaut, I'm going to go ahead and close this one - let us know if you're still having any issues with it.

Thanks!
Jon

**Comment by bdubaut** [comment]
For those who were interested, I added this line to my FeedEntry model in the method that saves the relevant entry information in the database (its obviously possible to do that all in the controller but I have a background job to update my feeds:
```ruby
images = Nokogiri::HTML(entry.summary).css('img')
image_url = images.first.attributes['src'].value
```

then I can display the image with no problem in the view.
