### ISSUE TITLE
Wont work in Rails 4.1.8

### ISSUE THREAD

**Issue by BrianBailey** [feedjira/feedjira#264]
very frustrating...   want to use this gem,   and have tried all the error messages and nothing works,   please need assistance    thanks   Brian

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    c:/RailsInstaller/Ruby2.0.0/bin/ruby.exe -r ./siteconf20150201-41296-12uswvu.rb extconf.rb
checking for curl-config... no
checking for main() in -lcurl... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=c:/RailsInstaller/Ruby2.0.0/bin/ruby
        --with-curl-dir
        --without-curl-dir
        --with-curl-include
        --without-curl-include=${curl-dir}/include
        --with-curl-lib
        --without-curl-lib=${curl-dir}/
        --with-curllib
        --without-curllib
extconf.rb:18:in `<main>':   Can't find libcurl or curl/curl.h (RuntimeError)

  Try passing --with-curl-dir or --with-curl-lib and --with-curl-include
  options to extconf.

extconf failed, exit code 1

Gem files will remain installed in c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/curb-0.8.6 for inspection.
Results logged to c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/extensions/x86-mingw32/2.0.0/curb-0.8.6/gem_make.out
An error occurred while installing curb (0.8.6), and Bundler cannot continue.
Make sure that `gem install curb -v '0.8.6'` succeeds before bundling.

**Comment by krasnoukhov** [comment]
Looks like `curb` gem fails to install on your Windows machine due to lack of `curl` library. Quick googling got me here, following instructions might help: https://github.com/taf2/curb/pull/233/files

**Comment by BrianBailey** [comment]
...   getting same error messages with gem 'curb'     or gem install curb     etc   
$ gem install curb
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing curb:
        ERROR: Failed to build gem native extension.

    c:/RailsInstaller/Ruby2.0.0/bin/ruby.exe -r ./siteconf20150201-40604-2tb6pc.rb extconf.rb
checking for curl-config... no
checking for main() in -lcurl... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

**Comment by amatriain** [comment]
Feedjira currently depends on the curb gem. The curb gem is a ruby wrapper around the curl binary, which is a program written in C. 

Before you can install the curb gem, your system must have a working installation of curl (along with development headers, I think), as documented here: https://github.com/taf2/curb#you-will-need

So, you should try to install curl on your system first. Forget about ruby, gem or bundler here, it's a plain C binary. If you use linux, simply use your package manager. Otherwise try using a binary installer for your OS from here: http://curl.haxx.se/download.html or try compiling it yourself following these instructions: http://curl.haxx.se/docs/install.html

After that you should be able to ```gem install curb``` and if that goes through follow with ```bundle install```

**Comment by jonallured** [comment]
Hi @BrianBailey, sorry you're having trouble installing the gem - @amatriain has some good suggestions for you about how to get `curb` installed, so take a look at that.

`curb` not playing nicely with Windows is just another reason why I've wanted to switch away from it to `faraday` where you can pick your networking backend. I've actually got this on a branch - you might want to check that out. By default `faraday` just uses's `Net::HTTP` from Ruby standard lib, so that could be a good fit for your situation.

```ruby
# in your Gemfile
gem 'feedjira', git: 'https://github.com/feedjira/feedjira.git', branch:'faraday'
```

Hope that helps!

**Comment by jonallured** [comment]
Hey @BrianBailey, I'm going to go ahead and close this one - if you're still having trouble let us know.

Thanks!
Jon

**Comment by damncraft** [comment]
had this problem on cloud9

```
Fetching: loofah-2.0.1.gem (100%)
Successfully installed loofah-2.0.1
Building native extensions.  This could take a while...
ERROR:  Error installing feedjira:
        ERROR: Failed to build gem native extension.

    /usr/local/rvm/rubies/ruby-2.1.5/bin/ruby -r ./siteconf20150210-24699-wbfbeg.rb extconf.rb
checking for curl-config... no
checking for main() in -lcurl... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/rvm/rubies/ruby-2.1.5/bin/ruby
        --with-curl-dir
        --without-curl-dir
        --with-curl-include
        --without-curl-include=${curl-dir}/include
        --with-curl-lib
        --without-curl-lib=${curl-dir}/lib
        --with-curllib
        --without-curllib
extconf.rb:18:in `<main>':   Can't find libcurl or curl/curl.h (RuntimeError)

  Try passing --with-curl-dir or --with-curl-lib and --with-curl-include
  options to extconf.

extconf failed, exit code 1

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/curb-0.8.6 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.1.5@rails4/extensions/x86_64-linux/2.1.0/curb-0.8.6/gem_make.out
```

**Comment by jonallured** [comment]
Hi @damncraft, I've never used Cloud9, but it looks like it's just a Ubuntu server and you can install stuff on it, so go ahead and install `curl`. Once you've got that installed, try this:

```
$ gem install curb
```

If that succeeds (and it should once `curl` is installed), then you should be good to go on installing Feedjira.

Thanks!
Jon

**Comment by damncraft** [comment]
ok find out the problem.
curl is installed by default on cloud9 - but the required package "libcurl4-gnutls-dev" isn't installed.
so we need:
```
sudo apt-get install libcurl4-gnutls-dev
```
My Cloud9 Workspace needs to update apt-get so u may need this too:
```
sudo apt-get update
```

After that - i could install curb and feedjira.

**Comment by tquill** [comment]
Ghost, thanks for the help.  I was having the same issue on cloud9.
