### ISSUE TITLE
unable to fetch and parse podcast cover art

### ISSUE THREAD

**Issue by mondaydreaming** [feedjira/feedjira#265]
Hi team feedjira!

I am trying to fetch and parse podcast cover art for xml files I have obtained from feedburner but the output saved in the @image variable is the audio file rather than cover art and there does not appear to be any other reference to pulling cover art image.

An example:

![screen shot 2015-02-10 at 11 09 50 am](https://cloud.githubusercontent.com/assets/9863107/6118791/7f1caf58-b115-11e4-97af-b85afa324012.png)

Thanks for your help!!

B

**Comment by jonallured** [comment]
Hi @mondaydreaming, I think what you're asking is for this URL to be returned:

```
http://www.thisamericanlife.org/sites/all/themes/thislife/images/logo-square-1400.jpg
```

That is the value of the `itunes:image` node inside the `channel` node. If that's right, then I think I've got an easy fix for you, but first let's review what Feedjira is doing by default. There are a number of parsers that ship with Feedjira and each one has it's own way of parsing an XML file. You can see which one is being used like this:

```ruby
url = 'http://feeds.thisamericanlife.org/talpodcast'
feed = Feedjira::Feed.fetch_and_parse url
feed.class
# => Feedjira::Parser::RSSFeedBurner
```

What this tells us is that the `Feedjira::Parser::RSSFeedBurner` class is what's determining our XML mappings. Go take a quick look at that class - what you'll notice is how few mappings are present. Not what we were hoping for. Plus, you know that this is a podcast and is using the iTunes format, so we'd much rather the `Feedjira::Parser::ITunesRSS` parser be used! You can force that to happen a couple different ways, maybe something like this:

```ruby
url = 'http://feeds.thisamericanlife.org/talpodcast'
xml = Feedjira::Feed.fetch_raw url
feed = Feedjira::Feed.parse_with Feedjira::Parser::ITunesRSS, xml
feed.class
# => Feedjira::Parser::ITunesRSS
```

Much better! And if you take a look at that class, you'll might notice it has a mapping from `itunes:image` to `itunes_image`, so you can access that image like so:

```ruby
# continued from above...
feed.itunes_image
# => "http://www.thisamericanlife.org/sites/all/themes/thislife/images/logo-square-1400.jpg"
```

Yay, we did it!! <3 <3 <3

**Comment by mondaydreaming** [comment]
Hi Jon!

Thank you so much for your speedy help, I sincerely appreciate it! You've
been a star :)

B

**Comment by jonallured** [comment]
Closing - let me know if you end up needing anything else on this.

**Comment by mondaydreaming** [comment]
Nope, all good :) Thanks so much for your help!

If you ever need help on the project that would be suitable for a beginner,
please let me know, I'd love to contribute!
