### ISSUE TITLE
Fixnum 200 error

### ISSUE THREAD

**Issue by ayilmaz4646** [feedjira/feedjira#266]
hi,
Fixnum 200 error and I can get feed the first time, but after I tried many times I cant get feed anymore.
 
http://localhost:3000/resque/failed
 
undefined method `entries' for 0:Fixnum
/home/ahmet/nimbo/feeder/app/models/feeder/feed_source.rb:16:in `get_entries'
/home/ahmet/nimbo/feeder/app/workers/feed_checker_worker.rb:8:in `perform'
 
"feeder_source.rb" piece of code:
    def get_entries
      new_feeds = Feedjira::Feed.fetch_and_parse(self.url)
      unless new_feeds.nil?
        unless new_feeds.entries.nil?
          new_feeds.entries.each do |entry|
            create_new_entry(entry, self.id)
          end
          #update_feed_source_info(new_feeds)
        else
          create_error(nil, nil, "no_entries")
        end
      else
        create_error(nil, nil, "rss_source_not_valid")
      end
    end
 
"feed_checker_worker.rb" piece of code:
  def self.perform(id)
    feed_source = Feeder::FeedSource.find(id)
    feed_source.get_entries
  end

**Comment by amatriain** [comment]
What is the URL?

**Comment by ayilmaz4646** [comment]
http://feeds.feedburner.com/FeldThoughts
https://signalvnoise.com/posts.rss
http://christinetsai.co/rss 
...

**Comment by jonallured** [comment]
Hi @ayilmaz4646, I tried to reproduce this, but I'm not getting `Fixnum`s back for those URLs.

```ruby
urls = ["http://feeds.feedburner.com/FeldThoughts", "https://signalvnoise.com/posts.rss", "http://christinetsai.co/rss"]
feeds = urls.map { |url| Feedjira::Feed.fetch_and_parse url }
puts feeds.map { |f| f.class }
# Feedjira::Parser::RSSFeedBurner
# Feedjira::Parser::RSS
# Feedjira::Parser::RSS
```

Are you still having this issue?

Thanks!
Jon

**Comment by jonallured** [comment]
Hi @ayilmaz4646 - I'm going to close this issue since I haven't heard back from you on it. If you end up needing anything else, just let me know.

Thanks!
Jon
