### ISSUE TITLE
Allow to inject HTTP client

### ISSUE THREAD

**Issue by RKushnir** [feedjira/feedjira#269]
Hello,
I think, it would be useful to provide a way to override the default `Curl::Multi` with other clients. My specific case requires mocking with WebMock. Unfortunately, `Curl::Multi` itself doesn't support mocking, so I'd like to replace it in the tests with something which does.

**Comment by amatriain** [comment]
@jonallured is currently working on a branch called ```faraday``` which replaces ```curb``` with ```faraday```. This branch no longer has a hardcoded dependency on ```Curl```, instead any HTTP gem supported by ```faraday``` can be used. It uses ```Net:HTTP``` by default.

I'm not familiar with ```webmock``` but it seems to support stubbing and setting expectations on ```Net:HTTP```, which I guess is what you need. You should try the ```faraday``` branch and see if it solves your problem.

See [here](https://github.com/feedjira/feedjira/issues/264#issuecomment-72471084) for a bit more information.

**Comment by RKushnir** [comment]
@amatriain Perfect, thank you!
Should I close the issue?

**Comment by amatriain** [comment]
I guess so, if your problem is solved.
