### ISSUE TITLE
Feeds failing to parse (200 Fixnum Error)

### ISSUE THREAD

**Issue by shalati** [feedjira/feedjira#274]
Hello,

Thanks for the great gem but I'm having trouble parsing the following feed:

http://newsroom.devry.edu/press+releases/rss.xml

If I use fetch_and_parse() method, I get the NoMethodError .entries on Fixnum(200) error.  If I fetch_raw, I can successfully fetch but then parsing raises "NoParserAvailable: No valid parser for XML".

The feed appears valid:

http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fnewsroom.devry.edu%2Fpress%2Breleases%2Frss.xml

Any ideas what's going wrong?

Thanks!

**Comment by shalati** [comment]
Okay, I have no idea why it is suddenly working...

**Comment by jonallured** [comment]
Hi @shalati, I'm going to assume this issue is resolved and close it, but let me know if you need anything else.

Thanks!
Jon
