### ISSUE TITLE
How to make Feedjira follow RSS redirects

### ISSUE THREAD

**Issue by tommybstitch** [feedjira/feedjira#275]
I am having an issue with some RSS feeds I am trying to parse with Feedjira getting redirected, but Feedjira fails to follow the redirect so parsing the RSS feed fails. Is there a way to get Feedjira to follow RSS redirects so these feeds no longer fail?

**Comment by amatriain** [comment]
As a workaround you can fetch the feed XML with any HTTP gem (e.g. RestClient automatically follows redirects). Then you can parse the response body with ```Feedjira::Feed.parse```.

**Comment by tommybstitch** [comment]
I did not even think of this - works like a charm. Thanks so much!
