### ISSUE TITLE
Feedjira::Feed.update does not work properly

### ISSUE THREAD

**Issue by tobiisdesired** [feedjira/feedjira#281]
I have the following example code:
<pre>
require 'feedjira'

feed = Feedjira::Feed.fetch_and_parse "http://lorem-rss.herokuapp.com/feed?unit=second&interval=30"
loop do
    feed = Feedjira::Feed.update(feed)
    puts feed.new_entries
    sleep 30
end
</pre>
The new entries show also old entries and grow in each iteration. Is this a bug, or  am I missing something important?

**Comment by jonallured** [comment]
Hi @tobiisdesired, you're not missing anything - the update stuff just doesn't work well and I usually advise people not use it. You can read my full rant here: #218, but let me know if you have any other questions.

Thanks!
Jon

**Comment by jonallured** [comment]
Hi @tobiisdesired, I'm going to go ahead and close this one. I did release version 2.0 today, which actually removes the update functionality because it never worked right anyway.

Thanks!
Jon

**Comment by tobiisdesired** [comment]
Hi @jonallured, thx for your reply. Keep up the good work.
