### ISSUE TITLE
Inconsistent return values from fetch

### ISSUE THREAD

**Issue by RKushnir** [feedjira/feedjira#282]
Hi,
When doing `fetch_raw` or `fetch_and_parse`, if the request is successful, it returns the expected feed content. However, when an error happens (e.g. page is not found, server is unavailable), it returns just an integer code of the error.
That's bad practice. How do you expect the user to check for errors?

Related code:
https://github.com/feedjira/feedjira/blob/d3340ccea8124466fba0ad8995152908d37fe8b1/lib/feedjira/feed.rb#L202
https://github.com/feedjira/feedjira/blob/d3340ccea8124466fba0ad8995152908d37fe8b1/lib/feedjira/feed.rb#L353

Related issues:
https://github.com/feedjira/feedjira/issues/274 https://github.com/feedjira/feedjira/issues/266 https://github.com/feedjira/feedjira/issues/259 https://github.com/feedjira/feedjira/issues/251 https://github.com/feedjira/feedjira/issues/219
and probably others

**Comment by jonallured** [comment]
Hi @RKushnir, I just released version 2.0 today and I think you'll find that it's much better about returning. When version 2.0 hits a problem with the url, you'll actually get a raised error!! :smile:
