### ISSUE TITLE
fetch_raw method is not working after updaing gem

### ISSUE THREAD

**Issue by dksaini14** [feedjira/feedjira#288]
I had received error after updating the gem:

NoMethodError (undefined method `fetch_raw' for Feedjira::Feed:Class):

Is this function exists?

**Comment by jonallured** [comment]
Hi @dksaini14 - that method was removed with version 2.0. The gem depends on `faraday`, so I would recommend something like this instead:

```ruby
response = Faraday.get url
# do something awesome with response
feed = Feedjira::Feed.parse response.body
```

I hope that helps and let me know if you need anything else on this.

Thanks!
Jon
