### ISSUE TITLE
How can I parse an RSS file

### ISSUE THREAD

**Issue by AlanDasein** [feedjira/feedjira#291]
I'm trying to parse an RSS file. It throws a 404 response when I do:

    Feedjira::Feed.fetch_and_parse url

So I thought trying:

    Feedjira::Parser::RSS.parse url

But that returns 0 entries

**Comment by amatriain** [comment]
Go to feedjira.com , there you have code examples. If you just want to parse a feed XML you've already fetched, look at the "just parse" section.

However, if you're fetching a feed and the server returns a 404 error, that probably means that the URL you're requesting doesn't actually exist. Feedjira cannot help you there, obviously.

**Comment by AlanDasein** [comment]
Hi. The url exists and it's being parsed successfully in another website from my company with PHP. I'm blind so far looking at how to do this either on feedjira.com or anywhere for that matter. I would like someone could tell me what implement instead of "Feedjira::Feed.fetch_and_parse url" (something like "Feedjira::Parser::RSS.parse url", but that returns 0 entries). Thank you.

**Comment by amatriain** [comment]
You have an example in feedjira.com , in the "just parsing" section, of how to fetch the feed using Faraday and then parse it with Feedjira.

My guess is that trying to fetch that URL with faraday will return a 404 error, before even trying to parse it with feedjira. Maybe that server is currently failing, or maybe it allows access only from certain IPs, or maybe it only accepts certain user-agent strings, among other possibilities.

**Comment by AlanDasein** [comment]
A guy from stackoverflow.com could access. It's probably the IPs restriction that you mentioned it. This is the url:

http://api.thenewsfunnel.com:3000/advanced-search/rss?markets=456,1276,2889,1421,1408,3483,1404,2987,2988,1423,1405,2989,1409,1417,1413,1418,2990,1402,3484,1422,1416,3485,106,101,2890,951,1414,2991,1420,3486,1415,1403,2820,1412,1419,1411&segments=23,756,191,27,24&p=0&item=30&token=202cb962ac59075b964b07152d234b70

**Comment by amatriain** [comment]
I can fetch and parse it without problem:

```
> f = Feedjira::Feed.fetch_and_parse 'http://api.thenewsfunnel.com:3000/advanced-search/rss?markets=456,1276,2889,1421,1408,3483,1404,2987,2988,1423,1405,2989,1409,1417,1413,1418,2990,1402,3484,1422,1416,3485,106,101,2890,951,1414,2991,1420,3486,1415,1403,2820,1412,1419,1411&segments=23,756,191,27,24&p=0&item=30&token=202cb962ac59075b964b07152d234b70'
> f.entries.count
 => 30
> f.title
 => "The News Funnel"
```

**Comment by AlanDasein** [comment]
I see. It's not a Feedjira issue at all. I'll close this thread then and figure out was going on. Thank you.

**Comment by AlanDasein** [comment]
Hi @amatriain can you delete your last comment? It shows my access token. Thank you.

**Comment by jonallured** [comment]
Hi @AlanDasein - I removed that comment, you're all set on this.

Thanks!
Jon
