### ISSUE TITLE
How to retrieve attributes

### ISSUE THREAD

**Issue by AlanDasein** [feedjira/feedjira#292]
I have this tag in my entries:

    <media:content medium="image" type="image/gif" url="url here" height="80" width="80"/>

How can I get the tag: ``media:content`` and its attribute ``url`` like I display the title?:

    <%= "#{entry.title}" %>

**Comment by AlanDasein** [comment]
I found the answer. I'll post it so if someone needs same info:

    Feedjira::Feed.add_common_feed_entry_element("media:content", :value => :url, :as => :pic)

That line before ``fetch_and_parse``.

**Comment by krasnoukhov** [comment]
@AlanDasein Please note that `add_common_feed_entry_element` should be called once. Calling it every time before the `fetch_and_parse` would create a memory leak.

**Comment by AlanDasein** [comment]
Thanks for the correction! I'm fetching just once, but I have it in mind.
