### ISSUE TITLE
JRuby test errors

### ISSUE THREAD

**Issue by jonallured** [feedjira/feedjira#293]
I was able to get Travis to behave and install then run the test suite, but now I'm getting weird test failures - see this Travis build:

https://travis-ci.org/feedjira/feedjira/builds/67585841

Only the JRuby jobs are failing. I took a shot at following the execution path through Sax Machine and Nokogiri, but quickly got lost. If anyone has any insight, it would be greatly appreciated!! :heart: :heart: :heart:

/cc @krasnoukhov

**Comment by mikeastock** [comment]
Closing for now. If anyone would like to work on this please feel free 😄
