### ISSUE TITLE
Timeout Options

### ISSUE THREAD

**Issue by ajkamel** [feedjira/feedjira#294]
In reference to #32 and #286 in respect to passing timeout options for faraday requests was this feature removed?   Does faraday have a default timeout where we would just catch the exception?

Would something like this work at line https://github.com/feedjira/feedjira/blob/master/lib/feedjira/feed.rb#L66-L66

``` ruby
def self.fetch_and_parse(url, options)
      response = connection(url).get do |req|
        req.options.timeout = options.timeout if options.timeout           # open/read timeout in seconds
        req.options.open_timeout = options.open_timeout if options.open_timeout      # connection open timeout in seconds
      end
      raise FetchFailure.new("Fetch failed - #{response.status}") unless response.success?
      xml = response.body
      parser_klass = determine_feed_parser_for_xml xml
      raise NoParserAvailable.new("No valid parser for XML.") unless parser_klass

      feed = parse_with parser_klass, xml
      feed.feed_url = url
      feed.etag = response.headers['etag'].to_s.gsub(/"/, '')
      feed.last_modified = response.headers['last-modified']
      feed
    end

```

**Comment by jonallured** [comment]
Yeah, I'm definitely interested in a patch that allows a configured Faraday object to be passed in, so I think you're on the right track here. My preference would be to not couple to specific Faraday options, but rather to allow a Feedjira user to pass in the connection.

Thoughts?

**Comment by ajkamel** [comment]
I agree I think this would be great moving forward if Faraday ever deprecates any of its methods.

**Comment by rcanand** [comment]
I realize this is still an open issue - but is there any way at this point to pass in timeout options to Feedjira fetch_and_parse?

**Comment by ajkamel** [comment]
@rcanand I've yet to take a reasonable stab at this due to time and other commitments but I would be open to feedback or someone taking this over.

**Comment by jonallured** [comment]
@rcanand don't forget - you can bypass Feedjira for the fetching altogether:

```ruby
conn = Faraday.new do |conn|
  conn.request.options.timeout = 20
end
response = conn.get(url)
xml = response.body
feed = Feedjira::Feed.parse xml
```

Hope that helps!
Jon

**Comment by mikeastock** [comment]
Longterm we are removing networking support from Feedjira so going to close this.
