### ISSUE TITLE
`fetch_and_parse': wrong number of arguments (2 for 1) (ArgumentError)

### ISSUE THREAD

**Issue by KelvinMutuma** [feedjira/feedjira#295]
I am getting the error above on 2.0.0. I have a method called fetch that accepts an array of feeds. 

```
   def fetch(feeds)

      Feedjira::Feed.fetch_and_parse(
            feeds, 
            {
              ssl_verify_peer: false,
              on_success: download_success,
              on_failure: log_error
            }
          )
   end 
```

When I call the method fetch(feed_array) I get an error

**`fetch_and_parse': wrong number of arguments (2 for 1) (ArgumentError)**

**Comment by KelvinMutuma** [comment]
Solved it by just doing a loop and feeding the parser with one feed url at a time and removing the other parameters. However now I get an error: ** `fetch_and_parse': No valid parser for XML. (Feedjira::NoParserAvailable**

**Comment by ddoolin** [comment]
`fetch_and_parse` only takes a single argument -- the URL -- as on the home page and source.

Each parser only does a simple RegEx check to determine whether or not it's able to parse the XML. Are you sure you're passing in valid XML (the base parser will accept pretty much any feed)? If you're using you're own parser, make sure it's been added with `add_feed_class`.

**Comment by jonallured** [comment]
Yeah, as @ddoolin says, I think you've got some XML that's not matching any of the built-in parsers. What I'd do is rescue that exception and figure out which feed is the offender. Then you can troubleshoot what's up.

Thanks!
Jon
