### ISSUE TITLE
Custom feed parser for one fetch

### ISSUE THREAD

**Issue by banesto** [feedjira/feedjira#303]
Is there a way to parse with custom parser just for one feed? I mean without adding custom parser as a new default parser. I guess I could use "parse_with", but I cannot find a "fetch" method without parsing

**Comment by jonallured** [comment]
Yeah, `parse_with` sounds like it would be perfect for what you're asking about. Is there a reason you don't want to use it?

**Comment by banesto** [comment]
How can I only fetch xml?

**Comment by jonallured** [comment]
How about something like this:

```ruby
xml = Faraday.get url
feed = Feedjira::Feed.parse_with parser, xml
```

**Comment by banesto** [comment]
It would be good to use Feedjira for that, not say Net::HTTP.

**Comment by banesto** [comment]
Thanks, it works with ```xml.body```
But how about making a method ```fetch```, that would be called in ```fetch_and_parse```? :smile_cat:

**Comment by jonallured** [comment]
Oh, right - that's what I get for going off of memory and not trying it myself! :D

Yeah, I know what you mean about having `fetch` and in was in the library prior to version 2. But it sorta seems silly for Feedjira to wrap Faraday in this way. You don't need an RSS parsing gem to make a network request, ya know?

**Comment by banesto** [comment]
Yes, agreed, but then again it wouldn't be silly to be able to call ```fetch_and_parse``` with custom parser argument.
