### ISSUE TITLE
Problem with fetching feeds

### ISSUE THREAD

**Issue by matthiasballreich** [feedjira/feedjira#304]
I use Stringer RSS App which uses feedjira and i have the problem that i could not add some RSS Feeds. For example this one: http://www.drwindows.de/external.php?do=rss&type=newcontent&sectionid=1&days=120&count=10

I openend a ticket in stringer git and there the developer (https://github.com/swanson/stringer/issues/380#issuecomment-177164847) says that the problem is related to feedjira. See his response there. So i hope you could fix it inside feedjira so that he could use the bugfixed version.

**Comment by jonallured** [comment]
Hey @matthiasballreich, sorry I can't help much here. :(

For one thing, Stringer is still on 1.3 and the gem is up to 2.0 - I can't be sure, but my guess is that they aren't interested in the newer version.

As @Koronen mentioned, they are passing arguments that are breaking this feed, so my feedback would be to see which of those is the culprit and then determine if it can be eliminated when fetching this feed.

Sorry I can't be of more help!!

Jon
