### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by udhayakumarm** [feedjira/feedjira#306]
Hi all,
        Iam a new in ruby on rails,I want to install the feedjira in peatio package. i find the website www.feedjira.com as contents i follow it . but where the place to write a code for feedjira.any one know the answer please tell me.

**Comment by jonallured** [comment]
Hi @udhayakumarm, I would be happy to help you - can you describe what you're trying to do in more detail? What have you tried? What error messages are you getting?

**Comment by karthickms** [comment]
Hi @jonallured,

- gem 'feedjira' in our package 

- bundle install in our terminal and what the next steps to reach it

**Comment by jonallured** [comment]
Once installed, you can fetch and parse a feed like this:

```ruby
url = "http://feedjira.com/blog/feed.xml"
feed = Feedjira::Feed.fetch_and_parse url
# => #<Feedjira::Parser::Atom...>
feed.title
# => "Feedjira Blog"
feed.url
# => "http://feedjira.com/blog"
feed.entries # returns an array of Entry objects
# => [<Feedjira::Feed::Entry ...>, <Feedjira::Feed::Entry ...>, ...]
```

Check out the site for more info: http://feedjira.com/ and let me know if you have any further questions.

**Comment by karthickms** [comment]
Hi @jonallured,

Thanks for your reply, Where should be placed the below code

url = "http://feedjira.com/blog/feed.xml"
feed = Feedjira::Feed.fetch_and_parse url
# => #<Feedjira::Parser::Atom...>
feed.title
# => "Feedjira Blog"
feed.url
# => "http://feedjira.com/blog"
feed.entries # returns an array of Entry objects
# => [<Feedjira::Feed::Entry ...>, <Feedjira::Feed::Entry ...>, ...]

**Comment by jonallured** [comment]
I guess I'm not sure what you mean - can you tell me more about what you're trying to do?

**Comment by karthickms** [comment]
I have installed using http://feedjira.com/,  followed below steps

gem 'feedjira' and
bundle install 

after that  the below codes displays on http://feedjira.com/, but those codes where should be placed?
Please help me

url = "http://feedjira.com/blog/feed.xml"
feed = Feedjira::Feed.fetch_and_parse url
# => #<Feedjira::Parser::Atom...>
feed.title
# => "Feedjira Blog"
feed.url
# => "http://feedjira.com/blog"
feed.entries # returns an array of Entry objects
# => [<Feedjira::Feed::Entry ...>, <Feedjira::Feed::Entry ...>, ...]

**Comment by jonallured** [comment]
Well, that's not much to go on, but if you're just trying to get started, you might want to create a file like this:

```ruby
# app/models/feed.rb

class Feed
  def initialize(url)
    @url = url
  end
  
  def entries
    Feedjira::Feed.fetch_and_parse(@url).entries
  end
end
```

Then, you'd be able to do something like this:

```ruby
# app/controllers/feeds_controller.rb

class FeedsController < ActionController::Base
  def index
    url = "http://feedjira.com/blog/feed.xml"
    feed = Feed.new url
    @entries = feed.entries
  end
end
```

And finally, you'd need a view:

```ruby
# app/views/feeds/index.erb

<ul>
  <% for entry in @entries %>
    <li><%= entry.title %>
  <% end %>
</ul>
```

That's all from memory, so forgive any syntax errors, etc. :D

You'd still need a route and all that, but that should at least get you going. Providing comprehensive support for integrating Feedjira into your project is a little outside the scope of this project, so I'm going to go ahead and close this issue. Good luck with your project.

**Comment by karthickms** [comment]
Hi @jonallured, 

That does work fine. But how to fetch the images I used following code for that,

<%= @images = Nokogiri::HTML(entry.content).css('img') %>  

But it displays only image tag like as,

<img src="http://s3.amazonaws.com/adamheroku_blog/foreman_screenshot.png" alt="Foreman screenshot" style="border: 2px solid #222">

But image not displayed
