### ISSUE TITLE
Fetch the images

### ISSUE THREAD

**Issue by karthickms** [feedjira/feedjira#307]
Hi all,

That does work fine. But how to fetch the images I used following code for that,

<%= @images = Nokogiri::HTML(entry.content).css('img') %>

But it displays only image tag not an image

**Comment by jonallured** [comment]
Hi @karthickms, this is not a Feedjira issue and the scope of this project doesn't include troubleshooting your application code.

**Comment by karthickms** [comment]
I follow the following code for get images not as image tag

<%= @images = Nokogiri::HTML(entry.content).css('img')
raw @images
 %>
