### ISSUE TITLE
Not supporting in Production server

### ISSUE THREAD

**Issue by karthickms** [feedjira/feedjira#308]
Hi all,

Following code is not support in production server

Feedjira::Feed.fetch_and_parse(@url).entries

When enter the code in my file, the blank page should be displayed 
i.e 500 internal server error shown

**Comment by jonallured** [comment]
Hi @karthickms, can you please provide more details about the problem you're having? A backtrace would really help too.

**Comment by karthickms** [comment]
Hi @jonallured,

It's working fine now. Because of database issues from my end
