### ISSUE TITLE
Sometimes my site is 500 internal server error happen

### ISSUE THREAD

**Issue by karthickms** [feedjira/feedjira#309]
Hi All,

Sometimes my site is 500 internal server error happen. Here I shared the screenshot

![2016-06-18 18-24-12](https://cloud.githubusercontent.com/assets/16956722/16170992/181fd576-3582-11e6-87a2-b37ef6e21a0c.png)

Please help me !!!!!....

**Comment by jonallured** [comment]
Hi @karthickms, as I said in #307, the scope of this project doesn't include troubleshooting your application code. Please limit your issues on this project to those that are particular to Feedjira.
