### ISSUE TITLE
Don't write warnings to stderr

### ISSUE THREAD

**Issue by PascalTurbo** [feedjira/feedjira#312]
If parsing of a datetime fails feedjira will write a warning to stderr. This behavior is relay annoying, because even if you create an application with crystal clear logging mechanism, feedjira will write some ugly messages without the necessary context for debugging to stderr. 
Shure it's possible to capture these messages and write them to somewhere else, but this doesn't look like a gentle way.

Personally I would prefer feedjira to throw an exception so I could handle the problem in my Application. Because there are others out there using feedjira in a different way, it could also be a solution to use a standard ruby logger and allow the application using feedjira to inject it's own logger.

**Comment by jonallured** [comment]
Sounds legit - you wanna send in a PR on this?

**Comment by PascalTurbo** [comment]
@jonallured I will. But what's the preferred way? Exceptions or logger?

**Comment by jonallured** [comment]
I'd go with exceptions. Seems more straightforward, don't you think?

**Comment by PascalTurbo** [comment]
D'oh! 

I've had a deeper look on what happened there and it isn't that easy. Throwing an exception would change the behavior of the library. At the moment, if parsing fails, there simply is no published or updated date. When throwing an exception, processing of the whole feed would fail.
So for working around the warning, a logger seems to be the only solution.
I will create an PR for this - and you can decide, if this fits the needs of feedjira.

**Comment by mikeastock** [comment]
@PascalTurbo can we close this now that we have logging?
