### ISSUE TITLE
last_modified sometimes is a String and sometimes a Time

### ISSUE THREAD

**Issue by PascalTurbo** [feedjira/feedjira#314]
Hi,

When last_modified is provided by the server response header, it's handled as a String but when there is no header for "last-modified" it's handled as a Time Object.

I could fix this and provide a PR but I need the expected Format. I prefer Time over String because otherwise the application using feedjira has to handle the parsing.

Bests
Pascal

**Comment by PascalTurbo** [comment]
No response to this?

**Comment by HParker** [comment]
Fixed by #313
