### ISSUE TITLE
atom feedburner seems to miss `link` url

### ISSUE THREAD

**Issue by jrochkind** [feedjira/feedjira#327]
AtomFeedBurner seems to be missing the `url` (not `feed_url`) for a feed. I think because it's looking for `element :link, :as => :url, :value => :href, :with => {:type => "text/html"}`, but feedburner is not (no longer?) putting the `type='text/html'` on the `link` tag anymore, at least for some feeds. 

I'm trying to figure out how to customize/monkey-patch this locally, but haven't gotten it yet.  I'm not sure if it should be fixed in master,  if it's a universal problem.  I'm not sure if there's any good way to get SaxParser to use the first link found if no link with proper type attribute is found.

**Comment by amatriain** [comment]
Can you give the URL of an example feed that has this problem?

**Comment by jrochkind** [comment]
Sure, http://feeds.feedburner.com/GiantRobotsSmashingIntoOtherGiantRobots

I have a bunch more too. The feeds you have in your test cases are still good, but there are newer feeds that aren't. I don't know if Feedburner has options somewhere, or treats feeds initialized a long time ago different than newer ones, or it depends on some quality of the original feed Feedburner is proxying, or what. 

It looks like just adding another `element` to catch just `link` works, although I'm not sure how it will effect the 'old style' feeds. Maybe the just `link` element should be first, so the original one overrides it if present, I think that might work?

**Comment by amatriain** [comment]
Sorry for all the noise, getting the automated validations to accept the pull request has been painful, I've had to close and reopen it several times.

@jrochkind , I've submitted a pull request that fixes the issue for the [http://feeds.feedburner.com/GiantRobotsSmashingIntoOtherGiantRobots](http://feeds.feedburner.com/GiantRobotsSmashingIntoOtherGiantRobots) feed, but I'd like to check that the fix works for other feeds. Could you fetch the ```fix-feedburner-url``` branch from [my fork of Feedjira](https://github.com/amatriain/feedjira/tree/fix-feedburner-url) and check it against other feeds that had this problem?

Or you can give me a list of those feeds you had identified that suffered this problem, and I can check the fix with them myself, as you prefer.
