### ISSUE TITLE
How and when do we release feedjira updates

### ISSUE THREAD

**Issue by HParker** [feedjira/feedjira#332]
I just started getting involved helping with feedjira. I am curious how and when we should be doing releases.

Also, I haven't been keeping a strict change log as things get merged. it might be worth making an addition in the change log with every PR that adds or changes functionality in a notable way.

**Comment by jonallured** [comment]
Hey @HParker, first of all: nice job stepping up and making this project better!! Your enthusiasm is much appreciated. 😄 

I took a look at my notes and this is what I wrote down for cutting new builds:

Steps for cutting a release:

* Ensure:
  * version is bumped
  * changelog is updated
  * tests pass

* Push to GitHub and see if Travis passes

* Tag the release and then push tags

* Build and push new gem:

```
$ gem build feedjira.gemspec
$ gem push <new-version-file>
```

* Tweet about it, linking to CHANGELOG

Probably worth putting somewhere, but yeah, that's the list I would use when I was cutting a new version of the gem.

**Comment by PascalTurbo** [comment]
My two cents about the "when":

* Critical Bugfixes: As fast as possible
* Uncritical Bugfixes and Feature enhancements: I think they should be available as a new Release within 4 Weeks. 

About the versioning I prefer the simple semantic:

* Bugfixes always increase the third level of the version number (2.0.0 -> 2.0.1)
* New Features increate the second level of the version number (2.0.0 -> 2.1.0)
* Features that breaks the compatibility to older version will become a new major Release.

**Comment by PascalTurbo** [comment]
If there are no other opinions on this, I would close the issue and say "let's do it so"

**Comment by HParker** [comment]
let's do it
