### ISSUE TITLE
2.1.0 Planning

### ISSUE THREAD

**Issue by HParker** [feedjira/feedjira#339]
We are nearly ready for 2.1.0

# Notable New Features

* Support for YouTube Atom
* Better itunes parsing
* Support for the oga handler

# Possible Additions
I would like to see, https://github.com/feedjira/feedjira/pull/276 and https://github.com/feedjira/feedjira/pull/313 merged possibly meaning we move jruby-9 from allowed failures to a supported platform? Not sure, but the builds look like supporting jruby would be possible.

# Prerelease Checklist

- [ ] Update the changelog.
- [ ] Write a post on the feedjira blog.
- [ ] Compare the benchmarks to the previous release. (possibly pause here if there are any performance regressions)

What else do we need for this release?

**Comment by PascalTurbo** [comment]
There are a bunch of already closed Pull Requests which didn't have the 2.1 Milestone Tag. I don't think, that we'll do a cherry pick release so we should add the Tag to all of the pull requests that happened since 2.0, shouldn't we?

**Comment by HParker** [comment]
I think updating the changelog is our next step. Tagging the PRs that go into the release also sounds like a great idea! 👍

**Comment by PascalTurbo** [comment]
How about the schedule of 2.1? I would love to see it released in 2016.

Creating the changelog is simple doing. I don't have any Idea how to create a blog post.
Benchmark regression is a good idea so far but with a look at the bunch of changes since the last release and the missing automated regression tests, we should skip this for 2.1 and enable benchmarking in our CI builds for the future.

**Comment by HParker** [comment]
@PascalTurbo we have benchmarks here: https://github.com/feedjira/feedjira-benchmarks

I haven't run them yet, so I suspect that would be a good place to start.

**Comment by HParker** [comment]
I am going through and adding the 2.1 mile stone to PRs I know would be helpful to have in the release notes.

**Comment by HParker** [comment]
2.1.0 is released 🎉 https://rubygems.org/gems/feedjira/versions/2.1.0
