### ISSUE TITLE
How to set configuration options

### ISSUE THREAD

**Issue by eappleby** [feedjira/feedjira#340]
In the Feedjira 2.0 announcement blog post, it says that if you want to set the user agent, that should be a configuration option. Can you provide an example of this? Ideally, I would like to mimic the options previously provided in Feedjira 1.0, including user_agent, if_modified_since, timeout, and ssl_verify_peer.

http://feedjira.com/blog/2014/04/14/thoughts-on-version-two-point-oh.html

**Comment by PascalTurbo** [comment]
As far as I see there is no way to set the user agent at the moment.

I like the idea setting the user agent from outside. I'm currently working at an configuration module for Feedjira. I'll have a look on this issue when finished.

**Comment by eappleby** [comment]
Thanks @PascalTurbo! In the meanwhile, I am fetching the HTTP request using Faraday and passing the User Agent that way. I posted an example here:

http://stackoverflow.com/a/40747524/1698908

**Comment by mikeastock** [comment]
@eappleby I actually just implemented what you are asking for in #360
