### ISSUE TITLE
Adding Code Documentation

### ISSUE THREAD

**Issue by PascalTurbo** [feedjira/feedjira#345]
Let's see this issue as a discussion point.

At the moment there is nearly no code documentation for Feedjira. 
I would prefer adding documentation for further development.

What are your opinions?

**Comment by HParker** [comment]
👍 are you imagining using something like YARD? I am all for it.

I also think it might be a good idea to move some of the docs from the website back into the README. At least enough to get started.

**Comment by PascalTurbo** [comment]
Yepp. I'm using YARD in all of my projects. 

I would initialize the "empty" yard setup. Afterwards we should say that only pull requests with meaningful comments are acceptable. I'll prepare a pull request for that ;)

I totally agree with you in the README Thing. I personally was always confused not to find the documentation on github. I'v just added some notes the the [README] (https://github.com/PascalTurbo/feedjira/blob/logger/README.md). Other opinions?
