### ISSUE TITLE
Strip whitespace inside elements

### ISSUE THREAD

**Issue by sferik** [feedjira/feedjira#350]
I noticed that many RSS feeds have extra whitespace (newlines, carriage returns, tabs, and spaces) within elements.

For example:

```xml
<title>

        All About Everything  

</title>
```

Feedjira will parse this into a Ruby string that is surrounded by whitespace:

```ruby
"\n\n        All About Everything\n\n"
```

To get around this issue, I’ve written Ruby code that looks like this:

```ruby
self.title = feed.title&.strip
self.author = feed.itunes_author&.strip
self.image = feed.itunes_image&.strip
self.subtitle = feed.itunes_subtitle&.strip
self.summary = feed.itunes_summary&.strip
self.description = feed.description&.strip
self.language = feed.language&.downcase&.strip
self.keywords = feed.itunes_keywords&.strip
```

Ideally, all of that stripping would be done in this library, so my code could look more like this:

```ruby
self.title = feed.title
self.author = feed.itunes_author
self.image = feed.itunes_image
self.subtitle = feed.itunes_subtitle
self.summary = feed.itunes_summary
self.description = feed.description
self.language = feed.language&.downcase
self.keywords = feed.itunes_keywords
```

Would this change be appropriate for the [2.1 milestone](https://github.com/feedjira/feedjira/milestone/1)?

If so, I can start working on this today.

**Comment by sferik** [comment]
@jonallured @PascalTurbo @HParker Any thoughts on this?

**Comment by HParker** [comment]
Yeah, seems less than ideal. Are there any cases where this whitespace would be significant?

**Comment by sferik** [comment]
@HParker Yeah, that’s what I’m asking. I can’t think of any, but if such cases exist, this would be a backwards-incompatible change and should probably be implemented as an option, instead of the default behavior.

For reference, [the XML specification has a section on whitespace](https://www.w3.org/TR/REC-xml/#sec-white-space). And [Sam Page has written an excellent interpretation and commentary on that spec](http://usingxml.com/Basics/XmlSpace).

I’m confident that stripping whitespace would be preferred by >= 99% of applications.

The question is: Will stripping it break 1% of applications or 0.0001% of applications (one in a million)?

**Comment by sferik** [comment]
Of course, that’s the specification for generic XML.

In Feedjira’s domain on RSS feeds, we know the semantics of specific elements. For example, a `<link>` should never contains newlines, carriage returns, tabs, or spaces. (A space may a valid character at the end of a URL, but it must be URL-encoded as `%20`.)

If someone is using Feedjira, I think the following error would be annoying and confusing:

```ruby
feed = Feedjira::Feed.parse_with(Feedjira::Parser::ITunesRSS, data)
URI.parse(feed.url)
# raises URI::InvalidURIError: bad URI(is not URI?):  http://example.com
# NOTE: The extra space ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```

**Comment by HParker** [comment]
I feel fairly confident that we should be able to remove whitespace from fields like links.

Right now I think the best plan of action would be to introduce it behind a config option in 2.1.1 and look at making it standard in a future major version.

How does that sound?

**Comment by PascalTurbo** [comment]
As @sferik said whitespaces in URLs are annoying (and there are real world feeds which produce such a garbage - so in my application a post-processing will happen). 

I could imagine a config option that takes a list of attributes (:link, :title, :author, ...) or a meta-attribute (:all) so it's possible to control it on a per user basis.

As all of these configuration things I'll link it to #340.
