### ISSUE TITLE
Trailing commas

### ISSUE THREAD

**Issue by mikeastock** [feedjira/feedjira#362]
Proposing a style change 

@HParker recommended we discuss style changes in a separate issue

**Comment by mikeastock** [comment]
This comes from #360

**Comment by HParker** [comment]
I generally feel that there should be a good reason to deviate from the rubocop style guide and so far I haven't felt strongly enough about trailing commas to require them. 🤔 I will stay open minded though. I know it makes git diffs much easier which is nice.

**Comment by PascalTurbo** [comment]
As described in #360 I think we should use [The Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide) as our basis like rubocop did.
It makes it easier for contributors to jump in contribution because it's widespread in the ruby world and well supported by rubocop.

**Comment by mikeastock** [comment]
Well sounds like I'm outnumbered so closing for now
