### ISSUE TITLE
Two-man rule for merging Pull Requests

### ISSUE THREAD

**Issue by PascalTurbo** [feedjira/feedjira#363]
I don't know how other projects handle this, but I would prefer a two-man rule for merging PRs. So that if one maintainer is creating a PR an other maintainer have to merge the PR.

**Comment by jonallured** [comment]
Yep, I agree with this.

**Comment by mikeastock** [comment]
Do we need the other maintainer to merge or at least approve?

**Comment by PascalTurbo** [comment]
@mikeastock as an answer to #361 
In this matter, I am torn. One the one hand side you're absolutely right - we shouldn't do micro management. On the other hand we would not have found the failures in the README without a second view.

About your Question here: I think an approval should fit. If the other maintainer is willing to merge - let him go.

**Comment by mikeastock** [comment]
@PascalTurbo do you feel like we can close this issue now?
