### ISSUE TITLE
Problems with utf-16 xmls

### ISSUE THREAD

**Issue by zealot128** [feedjira/feedjira#379]
I've tried importing this feed 
http://www.comparex-group.com/include/extensionsuser/feed/feed.aspx 
but received the ``Feedjira::NoParserAvailable`` exception.

That feed is encoded in UTF-16, which is written in the xml header:

```xml
<?xml version="1.0" encoding="utf-16"?>
```

unfortunately, Faraday does not try the automatic conversion, and all parser fail, as that line (and later <rss <atom lines) are written in ASCII like this ``"\xFF\xFE<\x00?\x00x\x00m\x00l\x00 \x00v\x00e\x00r\x00s\x00i\x00o\x00n\x00=\x00\"\x001\x00.\x000\x00\"\x00 \x00e\x00n\x00c\x00o\x00d\x00i\x00n\x00g\x00=\x00\"\x00u\x00t\x00f\x00-\x001\x006\x00\"\x00?\x00>\x00\r\x00\n"``, so the ``include?`` checks, that test for presence of rss fields of all the parsers does not work.

I found a work around like this:

```ruby
UTF_16_STRING = "utf-16".encode(Encoding::UTF_16).chars.drop(1).join.force_encoding(Encoding::ASCII_8BIT)

connection = Faraday.new do |conn|   
  conn.use FaradayMiddleware::FollowRedirects, limit: 3  
  conn.adapter :net_http
  conn.options.timeout = 4000
  conn.options.open_timeout = 4000                         
end                           
response = connection.get(feed_url) 
xml = response.body  
begin 
  if xml.include?(UTF_16_STRING)    
    xml = Nokogiri::XML.parse(xml).to_s.encode(Encoding::UTF_8)  
  end
rescue StandardError => e
end
parsed_feed = Feedjira::Feed.parse(xml)       
```                                                              

Ruby-Version: 2.2.3
feedjira 2.1.2
faraday 0.9.2
faraday_middleware 0.11.0.1

**Comment by mikeastock** [comment]
Longterm we are removing networking support from Feedjira so going to close this.
