### ISSUE TITLE
Support for JSON Feed?

### ISSUE THREAD

**Issue by jonathanpike** [feedjira/feedjira#387]
With the recent release of [JSON Feed](http://jsonfeed.org), I'm wondering if there has been any discussion as to whether Feedjira should support it? 

If this is something that could be supported, I'd be more than willing to provide a PR with my attempt at a solution.

**Comment by geraldb** [comment]
@jonathanpike  FYI: The alternative feed parser gem in ruby called [feedparser](https://github.com/feedparser/feedparser) has JSON Feed support added, see [builder/json](https://github.com/feedparser/feedparser/blob/master/lib/feedparser/builder/json.rb). Cheers.

**Comment by HParker** [comment]
I haven't played with JSON Feed much, but if it has a well defined spec I am totally open to supporting it!

**Comment by jonathanpike** [comment]
Added in #388
