### ISSUE TITLE
Failed to fetch some RSS source?

### ISSUE THREAD

**Issue by cqcn1991** [feedjira/feedjira#389]
I think this should not be the problem with feedjira itself, still, I want to know why this is happenning
```
url = 'http://www.coelevate.com/essays?format=RSS'
RSS::Parser.parse('http://www.coelevate.com/essays?format=RSS> #this works
Feedjira::Feed.fetch_and_parse(url) #this failed
```

**Comment by mahemoff** [comment]
It's probably an issue fetching the content, maybe SSL-related. Try using some other library to fetch the URL, e.g. `feed_string = open(url).read` with open-uri. Once you have the string, run `Feedjira::Feed.fetch(feed_string)`.

It's really only a Feedjira issue if you're able to fetch the URL with another library and fetch() breaks.
