### ISSUE TITLE
Nested dc:identifier is overwriting entry_id in RSSEntry

### ISSUE THREAD

**Issue by jschwindt** [feedjira/feedjira#393]
I'm trying to parse this feed: http://www.huffingtonpost.ca/feeds/index.xml which has `<media:content>` tag with a nested `<dc:identifier>` which happen to be always "1". The problem is that the `<dc:identifier>` is overwriting the entry_id with that "1" value.

Is there a way of avoiding overwriting the entry_id in such a situation. The entry_id is correctly detected from the `<guid>` and it'd be good if the overwriting doesn't happen if entry_id already has a value.

**Comment by HParker** [comment]
Fix merged via https://github.com/feedjira/feedjira/commit/f271648d6283ea9cd3191ba1456f3e45edac1091

Thanks for the issue!
