### ISSUE TITLE
Fail to parse date

### ISSUE THREAD

**Issue by GustavoCaso** [feedjira/feedjira#397]
We have a cron job at work that recursively fetches and parses RSS.
Lately, I have been getting a lot of `Fail to parse date` errors.

Could it be a way of silence those outputs? Is there a way to fix it? I guess by providing your own parser.

Thanks for the work is a fantastic gem.

**Comment by GustavoCaso** [comment]
I saw that you can configure a custom `logger` so I created a `NullLogger`

**Comment by mikeastock** [comment]
@GustavoCaso we also recently shipped a PR that changed the level those errors got parsed at. See #395. You should be able to set your logger to `info` and no longer see output from date parsing failures.
