### ISSUE TITLE
A samle code to parse on README fails to execute

### ISSUE THREAD

**Issue by owlworks** [feedjira/feedjira#401]
Hi. I tried a parse code according to README.
But it generated NoMethodError. Does this problem is on only of my environment?
(feedjira (2.1.4)/ ruby 2.2.3p173)

By the way, ``Feedjira::Feed.fetch_and_parse`` worked normally.

(After ``gem install feedjira``)
```
require 'feedjira'
require 'httparty'
url = 'https://hnrss.org/newest'
xml = HTTParty.get(url).body
feed = Feedjira.parse(xml)
feed.entries.first.title

=> undefined method `parse' for Feedjira:Module (NoMethodError)
```

**Comment by mikeastock** [comment]
Hey @owlworks! The README is actually for our 3.0 beta. The API for Feedjira changes in 3.0.

**Comment by owlworks** [comment]
I see, thanks you.

**Comment by ddacunha** [comment]
I understand that this is factually correct, but I think a warning on top of the README would be appreciated.
