### ISSUE TITLE
NoMethodError (undefined method `parse' for Feedjira:Module Did you mean?  parsers)

### ISSUE THREAD

**Issue by mohammedOmer** [feedjira/feedjira#411]
I get this message on parse rss xml file
```Feedjira.parse(xml)```

**Comment by thesubr00t** [comment]
Same here.

gem version 2.1.4

**Comment by mvanio** [comment]
Yep. Same. Version 2.1.4.

**Comment by memoht** [comment]
The error above seems to be because the Readme instructions have been updated to v3.0 which has not been released. 3.0 seems to have changed `Feedjira::Feed` to just `Feedjira`. I updated to `v3.00beta1` and am now greeted with:
```
Feedjira::NoParserAvailable (No valid parser for XML.)
```
Curses Batman.
