### ISSUE TITLE
An invalid XML character (Unicode: 0x3) was found in the CDATA section

### ISSUE THREAD

**Issue by sunloverz** [feedjira/feedjira#418]

**Comment by HParker** [comment]
Any chance you have more information or a reproduction I can use?

Thanks!

**Comment by sunloverz** [comment]


**Comment by sunloverz** [comment]
It fails to parse if feed's body consists of characters like red circles on the following picture.


![Untitled](https://user-images.githubusercontent.com/1597561/56199210-43ab4180-605e-11e9-99c1-0b0904efc78f.png)

**Comment by HParker** [comment]
@sunloverz The Stackoverflow you linked seems to indicate that that character is a control character that is not valid in XML. I don't plan on adding support for anything that does not work within the xml standard.

I am going to close for now, but feel free to comment again and clarify if I misunderstood.

**Comment by sunloverz** [comment]
So fixed an issue by forking this library and adding such code that removes invalid characters 
https://github.com/sunloverz/feedjira/blob/ver1.6.0/lib/feedjira/feed.rb#L313

**Comment by HParker** [comment]
@sunloverz ah, glad you got it working!

If you update to the latest version (2.2.0) you shouldn't need to do that anymore. You can do the sanitization in your own application code i.e. https://github.com/feedjira/feedjira#parsing in the readme.
