### ISSUE TITLE
`fetch_and_parse` method no longer supported on V3.0.0?

### ISSUE THREAD

**Issue by i2000s** [feedjira/feedjira#427]
Hello there,

I have bumped into v3.0.0, and this error occurred on me: `Liquid Exception: undefined method 'fetch_and_parse' for Feedjira::Feed:Class in XXX.html`. How to fix it? Thanks!

**Comment by i2000s** [comment]
An example of build failure on Travis-CI may be found [here](https://travis-ci.org/i2000s/en/builds/558077368?utm_medium=notification&utm_source=email).

**Comment by HParker** [comment]
Hey @i2000s, `fetch_and_parse` was removed in 3.0.0. Now Feedjira focuses on the thing that it is really good at which is parsing a variety of different feed formats!

You can change your code to look like the example in the [readme](https://github.com/feedjira/feedjira#parsing):

```ruby
xml = HTTParty.get(url).body
feed = Feedjira.parse(xml)
```

Hopefully that helps! Let me know. Please feel free to update the docs to make this more clear.

**Comment by i2000s** [comment]
@HParker Thank you for chiming in. I think I have fixed this problem. One extra step I did to fix this issue besides your hint is to add `gem "httparty"` into my Jekyll's `Gemfile` and to add `require 'httparty'` into my plugin (ruby code) file. Possibly it's better to claim the requirement of `httparty` in your `README.md` file, or maybe it's just my ignorance.

**Comment by ThomasConnolly** [comment]
RubyGems.org is still linking to "Homepage," which says version 2 was just released. Might want to kill that link, because it instructs "fetch_and_parse"
Thank you!

**Comment by HParker** [comment]
Thanks for letting me know @ThomasConnolly ! I updated it and released a new version, but rubygems hasn't picked it up yet. I'll check back tomorrow and hopefully it will have changed.
