### ISSUE TITLE
uninitialized constant Feedjira::FetchFailure -- How to resolve?

### ISSUE THREAD

**Issue by bobber205** [feedjira/feedjira#432]
I'm in a spot where I am rescuing for a couple errors.

`rescue Feedjira::NoParserAvailable, Feedjira::FetchFailure, Faraday::SSLError`

Recently started getting `uninitialized constant Feedjira::FetchFailure`

I see that's how it's referred to in the documentation but not sure how it's uninitialized now. 

Thanks for the help! Love the gem!

We're on version 3.1.0 FWIW

**Comment by HParker** [comment]
Hey @bobber205 would you be able to check your code for where you might be raising `Feedjira::FetchFailure`? we don't have that constant at all anymore. With the 3.0.0 release we removed a *lot* of the http code and instead ask you to do your own http, so it likely was removed with that.

**Comment by HParker** [comment]
I am assuming updating the library resolved this issue. Feel free to reopen if you have more information you want to add. :)
