### ISSUE TITLE
No #enclosure_url method for Podcast RSS

### ISSUE THREAD

**Issue by njh** [feedjira/feedjira#437]
Hi,

I have been trying to parse the RSS feed for [99% Invisible](https://99percentinvisible.org):
http://feeds.99percentinvisible.org/99percentinvisible

But the entries are are of class `Feedjira::Parser::RSSFeedBurnerEntry`, which does not have a `#enclosure_url` method.

Is there a way of working round this?

Thanks,

nick.

**Comment by njh** [comment]
I have found another example of this:
http://feeds.feedburner.com/TEDTalks_audio

As a work around to the problem, I had been using the `#image` method and then checking if the URL had `.mp3` in it.

However this RSS feed has both Images and MP3s in it - so there is no way of getting the MP3.

**Comment by HParker** [comment]
Hey @njh,

I seem to have a enclosure url for those feeds and the class seems to be `ITunesRSS` for me.

```ruby
require 'httparty'
require 'feedjira'

xml = HTTParty.get("http://feeds.99percentinvisible.org/99percentinvisible").body
feed = Feedjira.parse(xml)
feed.entries.first.enclosure_url
# => "https://dts.podtrac.com/redirect.mp3/media.blubrry.com/99percentinvisible/dovetail.prxu.org/96/3657a2b6-10a1-4580-8cce-ca8aff53b177/415_Goodnight_Nobody_pt01.mp3"
```

Can you provide a example of when you don't get the `#enclosure_url`?

**Comment by mockdeep** [comment]
These feeds both seem to be properly parsing the `enclosure_url` now. If you run into any other issues, feel free to open a new issue.

**Comment by njh** [comment]
Thanks for the [fix](https://github.com/feedjira/feedjira/commit/0fe5d8d6c5f72d434bc9bb69f66154c570c2cdb2) @mockdeep!

Confirmed working for me with version [3.2.2](https://rubygems.org/gems/feedjira/versions/3.2.2) of the feedjira gem 👍 

```
#!/usr/bin/env ruby

require 'net/http'
require 'feedjira'

uri = URI.parse('http://feeds.feedburner.com/TEDTalks_audio')
xml = Net::HTTP.get(uri)

feed = Feedjira.parse(xml)
feed.entries.each do |entry|
  puts entry.title
  puts "  Image: #{entry.image}"
  puts "  MP3: #{entry.enclosure_url}"
  puts
end
```
