### ISSUE TITLE
managingEditor should be managing_editor

### ISSUE THREAD

**Issue by davidwparker** [feedjira/feedjira#439]
Per Ruby standards, it should be camel_case (not to mention the rest of the project).

It's weird to be `managingEditor`

https://github.com/feedjira/feedjira/blob/b4543249cfacf7f20d860aae65eb7db35c9dd505/lib/feedjira/parser/itunes_rss.rb#L21

**Comment by gkpacker** [comment]
@davidwparker Hey there! I think this issue can be closed, since #443 is merged
