### ISSUE TITLE
Version 3.1.2 contains code that doesn't work on Ruby 2.4 and below

### ISSUE THREAD

**Issue by mvz** [feedjira/feedjira#447]
This line is not legal in older rubies: https://github.com/feedjira/feedjira/blob/master/lib/feedjira/date_time_utilities/date_time_pattern_parser.rb#L15

Perhaps this setting should be adjusted: https://github.com/feedjira/feedjira/blob/master/.rubocop.yml#L4

Rubocop didn't catch the mismatch with the supported set of Rubies due to this exclusion: https://github.com/feedjira/feedjira/blob/master/.rubocop.yml#L10

**Comment by mvz** [comment]
From #435 I conclude that the intent is to support Ruby 2.5 and up, so simplest fix would probably be to update the required ruby version in the gemspec.

**Comment by Ben-Fenner** [comment]
This caught me out today as rubygems.org still lists `feedjira` version `3.1.2` as compatible with Ruby 2.2. =/

https://rubygems.org/gems/feedjira/versions/3.1.2

**Comment by mockdeep** [comment]
@Ben-Fenner yeah, in retrospect we should have had a major version update before deprecating the older Ruby versions. I [spent a while](https://github.com/feedjira/feedjira/pull/491) just seeing what it would take to add back support for the older Ruby versions, and unfortunately it looks like it would take a lot of work to add support for older versions while also supporting newer ones.

**Comment by Ben-Fenner** [comment]
I'd be curious what it would take to get rubygems.org to update their specs. I have no idea how that works though. Do they introspect the code and determine things that way, in which case it would take rewriting git history on your gem to an insane degree to accomplish? Or can rubygems.org be sent an e-mail to update that one and that's all it takes? That would be the solution I'd be looking into anyway.

At the end of the day it worked out for me. Luckily this issue existed for me to research.

**Comment by mockdeep** [comment]
@Ben-Fenner RubyGems doesn't allow tampering with a gem version after it is released for the sake of security and reliability. We could yank the gem, but that would break anybody who is currently using that release. For better or worse, I think our best bet is to let this sit and hope that everybody is able to upgrade their Ruby version at some point.
