### ISSUE TITLE
Question: Does feedjira support Rails 7?

### ISSUE THREAD

**Issue by IsabelleLePivain** [feedjira/feedjira#487]
Apologies for the very plain question. From the issues and from my shallow look at feedjira's code, I cannot see any red flag. But I could not find either any explicit use of feedjira with Rails 7.

**Comment by mockdeep** [comment]
@IsabelleLePivain I'm using Feedjira on [a Rails 7.1 app](https://github.com/stringer-rss/stringer/). Feedjira doesn't have any Rails bindings, So the Rails version shouldn't matter.

**Comment by IsabelleLePivain** [comment]
Thank you @mockdeep !
